const ImageStore: Record<string, string> = {
  aero_v_dramonIcon: "/images/digimon/icon/aero-v-dramon.webp",
  agumon_blackIcon: "/images/digimon/icon/agumon-black.webp",
  agumonIcon: "/images/digimon/icon/agumon.webp",
  andromonIcon: "/images/digimon/icon/andromon.webp",
  big_mamemonIcon: "/images/digimon/icon/big-mamemon.webp",
  blacktyranomonIcon: "/images/digimon/icon/blacktyranomon.webp",
  etemonIcon: "/images/digimon/icon/etemon.webp",
  geo_greymonIcon: "/images/digimon/icon/geo-greymon.webp",
  geremonIcon: "/images/digimon/icon/geremon.webp",
  giga_warumonsaemonIcon: "/images/digimon/icon/giga-warumonsaemon.webp",
  gold_numemonIcon: "/images/digimon/icon/gold-numemon.webp",
  karatuki_numemonIcon: "/images/digimon/icon/karatuki-numemon.webp",
  kokuwamonIcon: "/images/digimon/icon/kokuwamon.webp",
  mamemonIcon: "/images/digimon/icon/mamemon.webp",
  mametyranoIcon: "/images/digimon/icon/mametyrano.webp",
  metal_greymon_vaccineIcon: "/images/digimon/icon/metal-greymon-vaccine.webp",
  metal_greymonIcon: "/images/digimon/icon/metal-greymon.webp",
  metal_mamemonIcon: "/images/digimon/icon/metal-mamemon.webp",
  monzaemonIcon: "/images/digimon/icon/monzaemon.webp",
  numemonIcon: "/images/digimon/icon/numemon.webp",
  pillowmonIcon: "/images/digimon/icon/pillowmon.webp",
  platinium_numemonIcon: "/images/digimon/icon/platinium-numemon.webp",
  rizegreymonIcon: "/images/digimon/icon/rizegreymon.webp",
  starmonIcon: "/images/digimon/icon/starmon.webp",
  sukamonIcon: "/images/digimon/icon/sukamon.webp",
  tekkamonIcon: "/images/digimon/icon/tekkamon.webp",
  tyranomonIcon: "/images/digimon/icon/tyranomon.webp",
  v_dramon_blackIcon: "/images/digimon/icon/v-dramon-black.webp",
  v_dramonIcon: "/images/digimon/icon/v-dramon.webp",
  waru_monzaemonIcon: "/images/digimon/icon/waru-monzaemon.webp",
  yuki_agumonIcon: "/images/digimon/icon/yuki-agumon.webp",
  yukidarumonIcon: "/images/digimon/icon/yukidarumon.webp",
  agumon: "/images/digimon/art/agumon.webp",
  kokuwamon: "/images/digimon/art/kokuwamon.webp",
};

export default ImageStore;
