import type { Metadata } from "next";
import "./globals.css";
import { SearchProvider } from "@/domains/search/context/search-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className="bg-black text-green-500">
        <main>
          <SearchProvider>{children}</SearchProvider>
        </main>
      </body>
    </html>
  );
}
